# PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else 'cpu')

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
var = torch.rand(7,7)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [15]:
var2 = torch.rand(1,7)

torch.matmul(var, var2.T)

tensor([[0.7571],
        [1.5783],
        [0.7994],
        [0.8766],
        [1.4257],
        [1.7675],
        [1.4308]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [23]:
# Set manual 
# Create two random tensors

torch.manual_seed(seed=42)
var = torch.rand(1,2)

torch.manual_seed(seed=42)
var2 = torch.rand(1,2)

print(var == var2)

# Matrix multiply tensors
torch.matmul(var,var2.T)

tensor([[True, True]])


tensor([[1.6156]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [99]:
# Set random seed on the GPU
torch.cuda.manual_seed(seed=1234)

var = torch.rand(1,2, device=device)

var, var

(tensor([[0.1272, 0.8167]], device='cuda:0'),
 tensor([[0.1272, 0.8167]], device='cuda:0'))


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed ^
torch.cuda.manual_seed_all(seed=42)
# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
var = torch.rand(2,3, device=device)
var2 = torch.rand(2,3, device=device)
# torch.rand(2,2,3)

var, var2

(tensor([[0.6130, 0.0101, 0.3984],
         [0.0403, 0.1563, 0.4825]], device='cuda:0'),
 tensor([[0.9877, 0.1289, 0.5621],
         [0.5221, 0.7445, 0.5955]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [141]:
# Perform matmul on tensor_A and tensor_B
res = torch.matmul(var, var2.T)
print(f"{res}, {res.size()}")

tensor([[0.8307, 0.5648],
        [0.3312, 0.4247]], device='cuda:0'), torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
res.max()

# Find min
res.min()

tensor(0.3312, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [150]:
# Find arg max
res.argmax()

# Find arg min
res.argmin()

tensor(2, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [165]:
# Set seed
torch.cuda.manual_seed(seed=42)

# Create random tensor
var = torch.rand(1,1,1,10, device=device)

# Remove single dimensions
var2 = var.squeeze()

# Print out tensors and their shapes
print(f"{var} {var.size()}")
print(f"{var2} {var2.size()}")


tensor([[[[0.6130, 0.0101, 0.3984, 0.0403, 0.1563, 0.4825, 0.7362, 0.4060,
           0.5189, 0.2867]]]], device='cuda:0') torch.Size([1, 1, 1, 10])
tensor([0.6130, 0.0101, 0.3984, 0.0403, 0.1563, 0.4825, 0.7362, 0.4060, 0.5189,
        0.2867], device='cuda:0') torch.Size([10])
