# Introduction to Tensors

In [45]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [2]:
# scalar
scalar = torch.tensor(7)
scalar.item() # tensor(7)

# vector
vector = torch.tensor([7,7]) # tensor([7, 7])
vector.ndim # 1
vector.shape # torch.Size([2])

# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]]) # tensor([[ 7,  8], [ 9, 10]])
MATRIX.ndim # 2
MATRIX[0]
MATRIX.shape # torch.Size([2, 2])

# TENSOR
TENSOR = torch.tensor([[ [1,2,3],
                         [3,6,9],
                         [2,4,5] ]])

TENSOR.shape # torch.Size([1, 3, 3])

torch.Size([1, 3, 3])

### Random Tensors

In [3]:
# Random tensors
random_tensor = torch.rand(3,4)
random_tensor

# random tensor similar to img tensor

random_img_size_tensor = torch.rand(size=(3, 224,224)) #  color_channel (r,g,b), hei, wid
random_img_size_tensor.shape, random_img_size_tensor.ndim # (torch.Size([224, 224, 3]), 3)

(torch.Size([3, 224, 224]), 3)

### 0's and 1's

In [4]:
zero = torch.zeros(2,2)
zero

ones = torch.ones(2,2)
ones.dtype # [default] torch.float32

torch.float32

### Range of tensors and tensor-like
    > use 'torch.arange' ('range': deprecated)

In [5]:
# tensor
zero_to_ten = torch.arange(0, 11, 2)
zero_to_ten # tensor([ 0,  2,  4,  6,  8, 10])
zero_to_ten.shape # torch.Size([6])

# tensor-like
six_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
six_zeros

tensor([0, 0, 0, 0, 0, 0])

## Tensor dtypes

In [11]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device="cuda", requires_grad=False)
float_32_tensor.dtype # torch.float32

# x32 - default (whole), x64 - more precision, x16 more speed, less precision, light

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype # torch.float16

(float_16_tensor * float_32_tensor).dtype

torch.float32

In [18]:
int_32_tensor = torch.tensor([3,4,9], dtype= torch.long)
int_32_tensor * int_32_tensor

tensor([ 9, 16, 81])

### Getting information from tensors

Tensors ... <br>
    not right datatype - tensor.dtype <br>
    not right shape - tensor.shape <br>
    not right device - tensor.device <br>


In [26]:
tensor = torch.rand(3,6).to('cuda')
print(tensor.dtype, tensor.shape, tensor.device)

torch.float32 torch.Size([3, 6]) cuda:0


### Manipulating tensors (operations)

+ add, - sub, / div, * mul, @ matmul

In [60]:
tensor = torch.tensor([1,2,3])
tensor + 10
torch.add(tensor, 10)
torch.matmul(tensor, tensor)
1*1 + 2*2 + 3*3

14

In [62]:
# loop, %% time

value = sum([(tensor[i] * tensor[i]) for i in range(len(tensor))])
value

tensor.matmul(tensor)
tensor @ tensor

tensor(14)

In [51]:

tensor_a = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float).to(device)
tensor_b = torch.tensor([[7, 10], [8, 11], [9, 12]], dtype=torch.float).to(device)

torch.matmul(tensor_a, tensor_b.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]], device='cuda:0')

Tensor Aggregation

In [80]:
x = torch.arange(0,100,10).type(torch.float32).to(device)

x.mean(), torch.mean(x)
x.min()
x.max()
x.sum()
x.argmax() # position of max
x[9]
x.argmin()

tensor(0, device='cuda:0')

Reshape, view, stack

In [114]:
x2 = torch.arange(1.,10.).to(device)
x2.reshape(1,9)

# view shares same memory, change view --original will change
x2_view = x2.view(1,9)

x2_stacked = torch.stack([x2,x2], dim=0)
x2_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]], device='cuda:0')

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2).to(device)

# squeeze - remove single dimension, unsqueeze add single dimension <(this, not this)>
x2.squeeze().unsqueeze(dim=0).shape

torch.Size([1, 9])

In [209]:
# permute - rearrange tensors order

x3 = torch.rand(size=(224,224,3))
x3_permuted = x3.permute(0,2,1)
x3_permuted.shape, x3.shape

(torch.Size([224, 3, 224]), torch.Size([224, 224, 3]))

In [212]:
x = torch.arange(1,10).reshape(1,3,3)
x[0,2,2], x[0][2][2]

x[:,1,0]
x[0,0,:]
x[0,:,2]
# x

tensor([3, 6, 9])

Reproducibility (random out of random)

In [252]:
x = torch.rand(3,4)
y = torch.rand(3,4)

random_seed = 42
torch.manual_seed(random_seed); z = torch.rand(3,4).to(device)
torch.manual_seed(random_seed); z1 = torch.rand(3,4).to(device)

z == z1

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]], device='cuda:0')

3:57